# Generated by Django 4.1.2 on 2022-10-26 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Volunteer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=100)),
                ('lname', models.CharField(max_length=100)),
                ('usrname', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=200)),
                ('instiname', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=15)),
                ('passwd', models.CharField(max_length=50)),
                ('cpasswd', models.CharField(max_length=50)),
            ],
        ),
    ]
